server:
  port: 8083
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/gzmu_bj?serverTimezone=UTC&characterEncoding=utf8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    dbcp2:
      initial-size: 5
      min-idle: 5
      max-total: 10
      max-wait-millis: 2000
  mvc:
    view:
      prefix: /
      suffix: .html
    static-path-pattern: /static/**
mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.gzmusxxy.entity
logging:
  level:
    com:
      gzmusxxy:
        mapper: debug
