server:
  port: 80
  tomcat:
    uri-encoding: UTF-8
spring:
  datasource:
    username: root
    password: zxcvbnm
    url: jdbc:mysql://127.0.0.1:3306/gzmu_bj?serverTimezone=GMT%2B8&characterEncoding=utf8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    dbcp2:
      initial-size: 5
      min-idle: 5
      max-total: 10
      max-wait-millis: 2000
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  servlet:
    multipart:
      max-request-size: 200MB
      max-file-size: 200MB
mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.gzmusxxy.entity
logging:
  level:
    com:
      gzmusxxy:
        mapper: debug
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
#ws:
#  fileUploadPath: D:/
